name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-validator:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Validate `index.html`
        run: |
          npm install -g html-validator
          html-validator --file=index.html --verbose
